services:
  immich-quiz:
    image: ghcr.io/rafaelsavi/immich-quiz:latest
    container_name: immich-quiz
    restart: unless-stopped
    ports:
      - "8010:8010"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
